services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bandbridge
    volumes:
      - db_data:/var/lib/postgresql/data
  audio:
    build:
      context: ./src/backend/audio
    restart: always
    depends_on:
      - db
    environment:
      - AUDIO_SERVICE_PORT=4001
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
    volumes:
      - asset_filestore:/assetfilestore
  admin:
    build:
      context: ./src/backend/admin
    restart: unless-stopped
    env_file:
      - ./src/backend/admin/.env
    ports:
      - "4002:4002"
    depends_on:
      - db
    volumes:
      - ./src/backend/admin/.env:/app/.env:ro
  web:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - AUDIO_SERVICE_URL=${AUDIO_SERVICE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    ports:
      - '3000:3000'
    depends_on:
      - db
      - audio
    volumes:
      - ./.env:/app/.env:ro
volumes:
  db_data:
  asset_filestore: 