services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bandbridge
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  audio:
    build:
      context: ./src/backend/audio
    restart: always
    depends_on:
      - db
    environment:
      - AUDIO_SERVICE_PORT=4001
      - AUDIO_FILESTORE_PATH=${AUDIO_FILESTORE_PATH}
    ports:
      - '4001:4001'
    volumes:
      - audio_filestore:${AUDIO_FILESTORE_PATH}
volumes:
  db_data:
  audio_filestore: 