FROM debian:bullseye

ARG AUDIOWAVEFORM_REF=master

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ffmpeg \
      ca-certificates \
      curl \
      git \
      cmake \
      g++ \
      libboost-all-dev \
      libtag1-dev \
      libmad0-dev \
      libsndfile1-dev \
      zlib1g-dev \
      pkg-config \
      make \
      libgd-dev \
      libid3tag0-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build

RUN git clone https://github.com/bbc/audiowaveform.git . && \
    git checkout "${AUDIOWAVEFORM_REF}" && \
    git submodule update --init --recursive || true && \
    if [ ! -d googletest ]; then \
      git clone https://github.com/google/googletest.git googletest; \
    fi && \
    cmake . && \
    make && \
    install -m 0755 /build/audiowaveform /usr/local/bin/audiowaveform

ENTRYPOINT ["/usr/local/bin/audiowaveform"]
